### ISSUE TITLE
Clarification on  devices

### ISSUE THREAD

**Issue by cn-johndpope** [TimoKinnunen/MauiXAMLBluetoothLE#7]
I see multiple bluetooth devices in my settings on android phone, should these appear in app? or is it just looking for heart beat bluetooth device?

**Comment by TimoKinnunen** [comment]
In file AndroidManifest.xml (Bluetooth Low Energy devices only):


<uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>


Already paired devices must be Heart Rate devices, because they contain 'HeartRateUuids.HeartRateServiceUuids':
IReadOnlyList<IDevice> systemDevices = Adapter.GetSystemConnectedOrPairedDevices(HeartRateUuids.HeartRateServiceUuids);

And scanning new Heart Rate devices, because they contain 'HeartRateUuids.HeartRateServiceUuids':
await Adapter.StartScanningForDevicesAsync(HeartRateUuids.HeartRateServiceUuids);

So the answer to your question is yes. You have several Heart Rate devices.

**Comment by cn-johndpope** [comment]
thanks so much
